apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: web
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        envFrom:
          - configMapRef:
              name: wordpress-cm
          - secretRef:
              name: wordpress-sec
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m" # 0.25 core
          limits:
            memory: "512Mi"
            cpu: "500m" # 0.5 core
        ports:
          - containerPort: 80
