apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: web
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate # Delete pods one by one and create new ones to ensure that at least one pod is running at all times
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-sec
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: database
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m" # 0.25 core
          limits:
            memory: "512Mi"
            cpu: "500m" # 0.5 core
        ports:
          - containerPort: 80
