apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: web
  labels:
    app: wordpress
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: wordpress
