apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: web
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31000
  selector:
    app: wordpress
