apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate # Delete pods one by one and create new ones to ensure that at least one pod is running at all times
  replicas: 1 # Number of pods to run
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.1.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: root-password
        resources:
          requests:
            memory: "2Gi"
            cpu: "1" # 1 core
          limits:
            memory: "4Gi"
            cpu: "2" # 2 cores
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-pv-storage
            mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
