apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      volumes:
        - name: mysql-pvc-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
      - image: mysql:8.1.0
        name: mysql
        envFrom:
          - configMapRef:
              name: mysql-cm
          - secretRef:
              name: mysql-sec
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m" # 0.25 core
          limits:
            memory: "512Mi"
            cpu: "500m" # 0.5 core
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-pvc-storage
            mountPath: "/var/lib/mysql"
