apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: wordpress
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce # only one node can mount the volume
  persistentVolumeReclaimPolicy: Retain # retain the volume after pod deletion
  storageClassName: mysql-sc # storage class name
  local:
    path: /mnt/data # path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms: # node selector terms
      - matchExpressions: # match expressions
        - key: disktype # label key
          operator: In # operator for the label
          values: 
          - local # label value
