apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: mysql-sc # storage class name
  accessModes:
    - ReadWriteOnce # only one node can mount the volume
  resources:
    requests:
      storage: 5Gi
